import '@/styles/globals.css'

import { MessageCircleWarningIcon } from 'lucide-react'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import React from 'react'

import { ThemeProvider } from '@/components/providers'
import { Badge } from '@/components/ui/badge'
import { NavTools } from '@/components/ui/nav-tools'
import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Danny Sinicco',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'bg-background text-foreground flex h-screen w-screen overflow-x-hidden font-sans antialiased ',
          'scrollbar scrollbar-track-primary scrollbar-thumb-secondary scrollbar-thumb-rounded-full',
          fontSans.variable
        )}
      >
        <Badge className='fixed left-1/2 top-4 z-50 -translate-x-1/2 gap-2 md:text-lg'>
          <MessageCircleWarningIcon />
          <p>Page under construction</p>
        </Badge>

        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <NavTools />
          <div className='relative inset-0 flex h-screen w-full select-none flex-col items-center justify-center'>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
